version: '3.8'
services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8880:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8
    container_name: symfony_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
